### ISSUE TITLE
Windows 7

### ISSUE THREAD

**Issue by harryray33** [t-mart/monoff#1]
Does this work with Win 7?

Thanks

**Comment by t-mart** [comment]
Windows compatibility is generally excellent across versions, so I'd strongly assume yes.

But, I tell you what: Could you test it for me and report back? Shouldn't take more than 15 seconds to download and try it. And, it wouldn't hurt if it doesn't work – it just would do nothing. With this information, I could add a blurb to the documentation about the supported versions of Windows.

**Comment by t-mart** [comment]
Feel free to reopen if you'd like to keep discussing.
